routes/web.php
<?php

Route::get('/', function () {
    return view('landing');
});

// Route::get('/', function () {
//     return view('auth.login');
// });

// Route::get('/register', function () {
//     return view('auth.register');
// });

Auth::routes();

//JADI INI GROUPING ROUTE, SEHINGGA SEMUA ROUTE YANG ADA DIDALAMNYA
//SECARA OTOMATIS AKAN DIAWALI DENGAN administrator
//CONTOH: /administrator/category ATAU /administrator/barang
Route::group([ 'middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home'); 
    //route diagnosis
    Route::resource('diagnosis', 'DiagnosaController')->except(['create', 'show']);
    Route::get('diagnosis/laporan','DiagnosaController@report');
    Route::post('diagnosis/proses', 'DiagnosaController@proses');

    //route diagnosis untuk pasien
    Route::post('diagnosis/pasien', 'DiagnosaPasienController@Index')->name('diagnosis.data');

    //route standar pertumbuhan
    Route::get('bbu','StandarController@indexBbu')->name('bbu.data');
    Route::get('pbu','StandarController@indexPbu')->name('pbu.data');
    Route::get('tbu','StandarController@indexTbu')->name('tbu.data');
    Route::get('bbpb','StandarController@indexBbpb')->name('bbpb.data');
    Route::get('bbtb','StandarController@indexBbtb')->name('bbtb.data');

    //route pasien
    Route::get('/pasien','PasienController@index')->name('pasien.index');
    Route::get('/pasien/add','PasienController@create');
    Route::post('/pasien/store','PasienController@store');
    Route::get('/pasien/edit/{id_pasien}','PasienController@edit');
    Route::post('/pasien/update/{id_pasien}','PasienController@update')->name('update');
    Route::get('/pasien/delete/{id_pasien}','PasienController@delete');
    Route::get('/pasien/detail/{id_pasien}','PasienController@detail');

    //rule
    Route::get('rule', 'RuleController@Index')->name('rule.data');
    Route::post('rule/add', 'RuleController@store')->name('rule.store');
    Route::get('rule/edit/{id}', 'RuleController@edit');
    Route::post('rule/update', 'RuleController@update')->name('rule.update');
    Route::get('rule/destroy/{id}', 'RuleController@destroy');

    //solusi
    Route::get('/solusi','SolusiController@index');
    Route::get('/solusi/edit/{id}','SolusiController@edit');
    Route::put('/solusi/update/{id}','SolusiController@update');

    //rekap status gizi
    Route::get('rekap', 'RekapController@Index')->name('rekap.data');
    Route::get('export', 'RekapController@export')->name('export');

    //user
    Route::resource('user', 'UserController')->except(['show']);
    Route::post('/user/store', 'UserController@store');
    //history
    Route::resource('history', 'HistoryController')->except(['create', 'show']);

    Route::get('/alamat/{kecamatan}','GiziController@a');

    Route::resource('coba', 'PasienController');
});

// Route::group([ 'middleware' => ['auth','checkLevel:admin']], function() {
//     //user
//     Route::resource('user', 'UserController')->except(['show']);
// });

app/Posyandu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Posyandu extends Model
{
    protected $table = 'posyandu';
}

app/Http/Controllers/PosyanduController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Redirect;
use Illuminate\Http\Request;
use App\User;
use Session;
use Auth;

class PosyanduController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/posyandu/posyandu.blade.php
@section('js')
<script type="text/javascript">
  $(document).ready(function() {
    $('#table').DataTable({
      "iDisplayLength": 50
    });

} );
</script>
@stop
@extends('layouts.app')

@section('content')
<div class="row">

  <div class="col-lg-2">
    <a href="{{ route('user.create') }}" class="btn btn-primary btn-rounded btn-fw"><i class="fa fa-plus"></i> Tambah User</a>
  </div>
    <div class="col-lg-12">
                  @if (Session::has('message'))
                  <div class="alert alert-{{ Session::get('message_type') }}" id="waktu2" style="margin-top:10px;">{{ Session::get('message') }}</div>
                  @endif
                  </div>
</div>
<div class="row" style="margin-top: 20px;">
<div class="col-lg-12 grid-margin stretch-card">
              <div class="card">

                <div class="card-body">
                  <h4 class="card-title">Data User</h4>
                  
                  <div class="table-responsive">
                    <table id="table" class="table table-striped">
                      <thead>
                        <tr>
                          <th>
                            Name
                          </th>
                          <th>
                            Username
                          </th>
                          <th>
                            Email
                          </th>
                          <th>
                            Created At
                          </th>
                          <th>
                            Action
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach($datas as $data)
                        <tr>
                          <td class="py-1">
                          @if($data->gambar)
                            <img src="{{url('images/user', $data->gambar)}}" alt="image" style="margin-right: 10px;" />
                          @else
                            <img src="{{url('images/user/default.png')}}" alt="image" style="margin-right: 10px;" />

                          @endif


                            {{$data->name}}
                          </td>
                          <td>
                          <a href="{{route('user.show', $data->id)}}"> 
                          {{$data->username}}
                          </a>
                          </td>
                          <td>
                            {{$data->email}}
                          </td>
                          <td>
                            {{$data->created_at}}
                          </td>
                          <td>
                           <div class="btn-group dropdown">
                          <button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action
                          </button>
                          <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 30px, 0px);">
                            <a class="dropdown-item" href="{{route('user.edit', $data->id)}}"> Edit </a>
                            <form action="{{ route('user.destroy', $data->id) }}" class="pull-left"  method="post">
                            {{ csrf_field() }}
                            {{ method_field('delete') }}
                            <button class="dropdown-item" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> Delete
                            </button>
                          </form>
                           
                          </div>
                        </div>
                          </td>
                        </tr>
                      @endforeach
                      </tbody>
                    </table>
                  </div>
                  {{-- {!! $datas->links() !!} --}}
                </div>
              </div>
            </div>
          </div>
@endsection